mkdir -p autonomous_vehicles/vehicle_architecture/powertrain_and_electrical_systems
mkdir -p autonomous_vehicles/vehicle_architecture/mechanical_subsystems
mkdir -p autonomous_vehicles/vehicle_architecture/on-board_computing_platform
mkdir -p autonomous_vehicles/sensing_and_perception/lidar
mkdir -p autonomous_vehicles/sensing_and_perception/radar
mkdir -p autonomous_vehicles/sensing_and_perception/cameras
mkdir -p autonomous_vehicles/sensing_and_perception/ultrasonic_and_inertial_sensors
mkdir -p autonomous_vehicles/sensing_and_perception/sensor_fusion
mkdir -p autonomous_vehicles/decision_and_planning/high-level_route_planning
mkdir -p autonomous_vehicles/decision_and_planning/behavior_planning
mkdir -p autonomous_vehicles/decision_and_planning/motion_planning_and_control
mkdir -p autonomous_vehicles/decision_and_planning/v2x_and_cooperative_driving
mkdir -p autonomous_vehicles/software_stack_and_architecture
mkdir -p autonomous_vehicles/safety_and_reliability/functional_safety
mkdir -p autonomous_vehicles/safety_and_reliability/cyber-physical_security
mkdir -p autonomous_vehicles/safety_and_reliability/fault_detection_and_isolation
mkdir -p autonomous_vehicles/safety_and_reliability/verification_and_validation_methods
mkdir -p autonomous_vehicles/human-machine_interaction
mkdir -p autonomous_vehicles/data_management_and_ethics
mkdir -p autonomous_vehicles/regulatory_and_legal_landscape
mkdir -p autonomous_vehicles/ecosystem_and_business_models


touch autonomous_vehicles/vehicle_architecture/powertrain_and_electrical_systems/battery_management.md
touch autonomous_vehicles/vehicle_architecture/powertrain_and_electrical_systems/electric_drive_electronics.md
touch autonomous_vehicles/vehicle_architecture/mechanical_subsystems/steering_and_suspension.md
touch autonomous_vehicles/vehicle_architecture/mechanical_subsystems/braking.md
touch autonomous_vehicles/vehicle_architecture/on-board_computing_platform/cpu_gpu_asic_architectures.md
touch autonomous_vehicles/vehicle_architecture/on-board_computing_platform/edge-to-cloud_data_pipelines.md
touch autonomous_vehicles/sensing_and_perception/lidar/point-cloud_processing.md
touch autonomous_vehicles/sensing_and_perception/lidar/calibration_and_registration.md
touch autonomous_vehicles/sensing_and_perception/radar/target_detection_and_tracking.md
touch autonomous_vehicles/sensing_and_perception/radar/doppler_velocity_estimation.md
touch autonomous_vehicles/sensing_and_perception/cameras/image_segmentation_and_object_detection.md
touch autonomous_vehicles/sensing_and_perception/cameras/depth_estimation_slam.md
touch autonomous_vehicles/sensing_and_perception/ultrasonic_and_inertial_sensors/imu_fusion.md
touch autonomous_vehicles/sensing_and_perception/ultrasonic_and_inertial_sensors/proximity_detection.md
touch autonomous_vehicles/sensing_and_perception/sensor_fusion/bayesian_filters.md
touch autonomous_vehicles/sensing_and_perception/sensor_fusion/deep-learning_fusion_layers.md
touch autonomous_vehicles/decision_and_planning/high-level_route_planning/map-based_path_generation.md
touch autonomous_vehicles/decision_and_planning/high-level_route_planning/dynamic_re-planning.md
touch autonomous_vehicles/decision_and_planning/behavior_planning/rule-based_vs_ml_policies.md
touch autonomous_vehicles/decision_and_planning/behavior_planning/ethical_decision_modules.md
touch autonomous_vehicles/decision_and_planning/motion_planning_and_control/trajectory_generation.md
touch autonomous_vehicles/decision_and_planning/motion_planning_and_control/low-level_controllers.md
touch autonomous_vehicles/decision_and_planning/v2x_and_cooperative_driving/dsrc_c-v2x_protocols.md
touch autonomous_vehicles/decision_and_planning/v2x_and_cooperative_driving/platooning_and_intersection_coordination.md
touch autonomous_vehicles/software_stack_and_architecture/operating_systems.md
touch autonomous_vehicles/software_stack_and_architecture/middleware_and_communication.md
touch autonomous_vehicles/software_stack_and_architecture/real-time_task_scheduling.md
touch autonomous_vehicles/software_stack_and_architecture/continuous_integration_deployment_pipelines.md
touch autonomous_vehicles/safety_and_reliability/functional_safety/hazard_analysis.md
touch autonomous_vehicles/safety_and_reliability/functional_safety/safety_integrity_levels.md
touch autonomous_vehicles/safety_and_reliability/cyber-physical_security/secure_boot_firmware_attestation.md
touch autonomous_vehicles/safety_and_reliability/cyber-physical_security/intrusion_detection_systems.md
touch autonomous_vehicles/safety_and_reliability/fault_detection_and_isolation/redundancy_strategies.md
touch autonomous_vehicles/safety_and_reliability/fault_detection_and_isolation/self-diagnostics.md
touch autonomous_vehicles/safety_and_reliability/verification_and_validation_methods/simulation_and_digital_twins.md
touch autonomous_vehicles/safety_and_reliability/verification_and_validation_methods/hardware-in-the-loop_testing.md
touch autonomous_vehicles/human-machine_interaction/driver_monitoring_systems.md
touch autonomous_vehicles/human-machine_interaction/in-vehicle_infotainment_and_ux_design.md
touch autonomous_vehicles/human-machine_interaction/transition_management.md
touch autonomous_vehicles/data_management_and_ethics/data_collection,_labeling,_and_storage.md
touch autonomous_vehicles/data_management_and_ethics/privacy-preserving_techniques.md
touch autonomous_vehicles/data_management_and_ethics/bias_mitigation_in_perception_models.md
touch autonomous_vehicles/regulatory_and_legal_landscape/international_standards.md
touch autonomous_vehicles/regulatory_and_legal_landscape/liability_frameworks.md
touch autonomous_vehicles/regulatory_and_legal_landscape/deployment_policies_and_testing_regulations.md
touch autonomous_vehicles/ecosystem_and_business_models/mobility-as-a-service_platforms.md
touch autonomous_vehicles/ecosystem_and_business_models/infrastructure_requirements.md
touch autonomous_vehicles/ecosystem_and_business_models/partnerships.md